"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[ ](fg:color_orange)\
[](color_yellow)\
$directory\
[ ](fg:color_yellow)\
([](color_aqua)\
$git_branch\
$git_status\
[ ](fg:color_aqua))\
([](color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ ](fg:color_blue))\
([](color_bg3)\
$docker_context\
$conda\
$pixi\
[ ](fg:color_bg3))\
[](color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg0 = '#282828'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_bg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_bg0"
style_root = "bg:color_orange fg:color_bg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:color_bg0 bg:color_aqua"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_bg0 bg:color_aqua"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[cpp]
symbol = " "
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:color_bg0 bg:color_blue"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "fg:#83a598 bg:color_bg3"
format = '[ $symbol( $context) ]($style)'

[conda]
style = "fg:#83a598 bg:color_bg3"
format = '[ $symbol( $environment) ]($style)'

[pixi]
style = "fg:color_fg0 bg:color_bg3"
format = '[ $symbol( $version)( $environment) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg0 bg:color_bg1"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold fg:color_green)'
error_symbol = '[>](bold fg:color_red)'
vimcmd_symbol = '[<](bold fg:color_green)'
vimcmd_replace_one_symbol = '[<](bold fg:color_purple)'
vimcmd_replace_symbol = '[<](bold fg:color_purple)'
vimcmd_visual_symbol = '[<](bold fg:color_yellow)'